"""Gate: repo.schema-snapshot — freeze the canonical Phase 2/3 row schema.

Renders the two canonical contract rows (``build_d1_rest_api_list_row`` and
``build_call_row`` from ``igc/ds/rest_goal_contract.py``) with a fixed
in-gate fixture, reduces each to a *shape* (structure + key names + value types,
never fixture values), and compares that shape to a committed snapshot. Any change
to the approved JSON example shape — a renamed/added/removed field, a changed
nesting — fails the gate until the snapshot is deliberately regenerated with
``--update``. This is the "approved JSON examples don't drift silently" half of the
contract protection; the sibling gate ``repo.contract-single-source`` forbids
parallel contract modules and forked namespaces.

Bootstrap note: the committed snapshot must be generated by ``--update`` on an
approved execution surface (CI or a GB300 container), never on the operator
laptop. Until it exists, ``--check`` exits 3 (BOOTSTRAP) rather than passing.

Used by ``.github/workflows/ci.yml`` (gate job) and the platform gate registry.

Author:
Mus mbayramo@stanford.edu
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

EXIT_OK = 0
EXIT_FAIL = 1
EXIT_BOOTSTRAP = 3

# Fixed, deterministic fixture. Changing it is a deliberate snapshot change.
_FIXTURE_REST_API = "/redfish/v1/Systems/1"
_FIXTURE_TEXT = "power on system 1"


def build_canonical_rows() -> dict[str, Any]:
    """Build the two canonical rows from the fixed fixture.

    :return: ``{"phase2": <row>, "phase3": <row>}`` using the canonical builders.
    """
    from igc.ds.rest_goal_contract import (
        RedfishContext,
        build_call_row,
        build_d1_rest_api_list_row,
    )

    contexts = [
        RedfishContext(
            rest_api=_FIXTURE_REST_API,
            allowed_methods=["GET", "PATCH"],
            json={"@odata.id": _FIXTURE_REST_API, "PowerState": "On"},
        )
    ]
    phase2 = build_d1_rest_api_list_row(
        text=_FIXTURE_TEXT,
        contexts=contexts,
        rest_api_list=[_FIXTURE_REST_API],
    )
    phase3 = build_call_row(
        text=_FIXTURE_TEXT,
        contexts=contexts,
        rest_api_list=[_FIXTURE_REST_API],
        method_by_api={_FIXTURE_REST_API: "PATCH"},
        arguments_by_api={_FIXTURE_REST_API: {"PowerState": "On"}},
    )
    return {"phase2": phase2, "phase3": phase3}


def schema_shape(value: Any) -> Any:
    """Reduce a JSON value to a fixture-independent shape (structure + types).

    Scalars become their type name so fixture values never enter the snapshot;
    dict keys and nesting ARE preserved, because a renamed/added/removed field is
    exactly the drift this gate must catch.

    :param value: any JSON-compatible value.
    :return: the shape (nested dict/list of type-name strings).
    """
    if isinstance(value, dict):
        return {key: schema_shape(value[key]) for key in sorted(value)}
    if isinstance(value, list):
        return [schema_shape(item) for item in value]
    if isinstance(value, bool):
        return "bool"
    if value is None:
        return "null"
    if isinstance(value, int):
        return "int"
    if isinstance(value, float):
        return "float"
    return "str"


def current_shape() -> dict[str, Any]:
    """Return the shape of the canonical rows rendered from the fixed fixture."""
    return {name: schema_shape(row) for name, row in build_canonical_rows().items()}


def _render(shape: dict[str, Any]) -> str:
    """Serialize a shape to a stable, diff-friendly JSON string."""
    return json.dumps(shape, indent=2, sort_keys=True) + "\n"


def update(snapshot_path: Path) -> int:
    """Regenerate the committed snapshot from the current canonical shape."""
    snapshot_path.parent.mkdir(parents=True, exist_ok=True)
    snapshot_path.write_text(_render(current_shape()), encoding="utf-8")
    print(f"OK: wrote schema snapshot {snapshot_path}")
    return EXIT_OK


def check(snapshot_path: Path) -> int:
    """Compare the current canonical shape to the committed snapshot.

    :return: ``EXIT_OK`` on match, ``EXIT_FAIL`` on drift, ``EXIT_BOOTSTRAP`` when
        the snapshot has not been generated yet.
    """
    if not snapshot_path.is_file():
        print(
            "BOOTSTRAP: schema snapshot not committed yet; run "
            f"`python scripts/gates/schema_snapshot.py --update` on an approved surface "
            f"(CI or GB300 container) and commit {snapshot_path}.",
            file=sys.stderr,
        )
        return EXIT_BOOTSTRAP
    expected = snapshot_path.read_text(encoding="utf-8")
    actual = _render(current_shape())
    if expected == actual:
        print("OK: canonical Phase 2/3 row schema matches the committed snapshot.")
        return EXIT_OK
    print("BLOCKER: canonical Phase 2/3 row schema drifted from the committed snapshot.", file=sys.stderr)
    print("  regenerate deliberately with --update if the change is intended.", file=sys.stderr)
    return EXIT_FAIL


def main(argv: list[str] | None = None) -> int:
    """CLI entry point for the ``repo.schema-snapshot`` gate."""
    parser = argparse.ArgumentParser(description="Freeze the canonical Phase 2/3 row schema.")
    parser.add_argument(
        "--snapshot",
        default="schemas/snapshots/rest_goal_contract.shape.json",
        help="Path to the committed schema-shape snapshot.",
    )
    parser.add_argument("--update", action="store_true", help="Regenerate the snapshot from the contract.")
    args = parser.parse_args(argv)

    snapshot_path = Path(args.snapshot)
    if args.update:
        return update(snapshot_path)
    return check(snapshot_path)


if __name__ == "__main__":
    raise SystemExit(main())


# Author: Mus mbayramo@stanford.edu
